// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"
	modelsuperapp "onmi/internal/model/superapp"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Transport is an autogenerated mock type for the Transport type
type Transport struct {
	mock.Mock
}

type Transport_Expecter struct {
	mock *mock.Mock
}

func (_m *Transport) EXPECT() *Transport_Expecter {
	return &Transport_Expecter{mock: &_m.Mock}
}

// GetLimits provides a mock function with given fields:
func (_m *Transport) GetLimits() (uint64, time.Duration) {
	ret := _m.Called()

	var r0 uint64
	var r1 time.Duration
	if rf, ok := ret.Get(0).(func() (uint64, time.Duration)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() time.Duration); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	return r0, r1
}

// Transport_GetLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimits'
type Transport_GetLimits_Call struct {
	*mock.Call
}

// GetLimits is a helper method to define mock.On call
func (_e *Transport_Expecter) GetLimits() *Transport_GetLimits_Call {
	return &Transport_GetLimits_Call{Call: _e.mock.On("GetLimits")}
}

func (_c *Transport_GetLimits_Call) Run(run func()) *Transport_GetLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transport_GetLimits_Call) Return(n uint64, p time.Duration) *Transport_GetLimits_Call {
	_c.Call.Return(n, p)
	return _c
}

func (_c *Transport_GetLimits_Call) RunAndReturn(run func() (uint64, time.Duration)) *Transport_GetLimits_Call {
	_c.Call.Return(run)
	return _c
}

// Process provides a mock function with given fields: ctx, batch
func (_m *Transport) Process(ctx context.Context, batch modelsuperapp.Batch) error {
	ret := _m.Called(ctx, batch)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, modelsuperapp.Batch) error); ok {
		r0 = rf(ctx, batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transport_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type Transport_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - batch modelsuperapp.Batch
func (_e *Transport_Expecter) Process(ctx interface{}, batch interface{}) *Transport_Process_Call {
	return &Transport_Process_Call{Call: _e.mock.On("Process", ctx, batch)}
}

func (_c *Transport_Process_Call) Run(run func(ctx context.Context, batch modelsuperapp.Batch)) *Transport_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(modelsuperapp.Batch))
	})
	return _c
}

func (_c *Transport_Process_Call) Return(_a0 error) *Transport_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transport_Process_Call) RunAndReturn(run func(context.Context, modelsuperapp.Batch) error) *Transport_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransport creates a new instance of Transport. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransport(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transport {
	mock := &Transport{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
