---
name: 'Onmi: Unit tests and Linter'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  # Unit tests #######################################################################
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout git repo
        uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21'

      - name: Run unit tests
        run: make test-unit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover.out
          verbose: true
          fail_ci_if_error: true
          flags: onmi

  # Linter #############################################################################
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21'

      - name: Checkout git repo
        uses: actions/checkout@v4.1.1

      - name: Install lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.0

      - name: Run lint
        run: ./bin/golangci-lint run --out-format=tab  ./...


